export enum RunState {
  DRAFT = 'DRAFT',
  PLANNING = 'PLANNING',
  ROUTING = 'ROUTING',
  EXECUTING = 'EXECUTING',
  WAITING_APPROVAL = 'WAITING_APPROVAL',
  RETRYING = 'RETRYING',
  PAUSED = 'PAUSED',
  FAILED = 'FAILED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum TaskState {
  PENDING = 'PENDING',
  QUEUED = 'QUEUED',
  DISPATCHED = 'DISPATCHED',
  RUNNING = 'RUNNING',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED',
  SKIPPED = 'SKIPPED',
  CANCELLED = 'CANCELLED',
}

export enum ApprovalState {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}

export enum FailureType {
  PROVIDER_ERROR = 'PROVIDER_ERROR',
  TIMEOUT = 'TIMEOUT',
  INVALID_OUTPUT = 'INVALID_OUTPUT',
  BUDGET_EXCEEDED = 'BUDGET_EXCEEDED',
  POLICY_DENIED = 'POLICY_DENIED',
  APPROVAL_REJECTED = 'APPROVAL_REJECTED',
  SANDBOX_ERROR = 'SANDBOX_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}

export enum RiskLevel {
  SAFE = 'SAFE',
  ELEVATED = 'ELEVATED',
  HIGH_RISK = 'HIGH_RISK',
  BLOCKED = 'BLOCKED',
}

export enum RoutingStrategy {
  USER_SELECTED = 'USER_SELECTED',
  ROLE_DEFAULT = 'ROLE_DEFAULT',
  LOCAL_FIRST = 'LOCAL_FIRST',
  CLOUD_FIRST = 'CLOUD_FIRST',
  COST_AWARE = 'COST_AWARE',
  FALLBACK_CHAIN = 'FALLBACK_CHAIN',
}

export enum ProviderType {
  OLLAMA = 'OLLAMA',
  GEMINI = 'GEMINI',
  ANTHROPIC = 'ANTHROPIC',
  OPENAI_COMPATIBLE = 'OPENAI_COMPATIBLE',
  GENERIC_HTTP = 'GENERIC_HTTP',
}

export enum AgentRole {
  PLANNER = 'PLANNER',
  RESEARCHER = 'RESEARCHER',
  BUILDER = 'BUILDER',
  REVIEWER = 'REVIEWER',
  OPERATIONS = 'OPERATIONS',
}

export enum EventType {
  RUN_STATE_CHANGED = 'RUN_STATE_CHANGED',
  TASK_STATE_CHANGED = 'TASK_STATE_CHANGED',
  PROVIDER_CALL_STARTED = 'PROVIDER_CALL_STARTED',
  PROVIDER_CALL_COMPLETED = 'PROVIDER_CALL_COMPLETED',
  PROVIDER_CALL_FAILED = 'PROVIDER_CALL_FAILED',
  TOOL_REQUEST = 'TOOL_REQUEST',
  TOOL_RESULT = 'TOOL_RESULT',
  APPROVAL_REQUESTED = 'APPROVAL_REQUESTED',
  APPROVAL_RESOLVED = 'APPROVAL_RESOLVED',
  POLICY_EVALUATED = 'POLICY_EVALUATED',
  CHECKPOINT_CREATED = 'CHECKPOINT_CREATED',
  BUDGET_WARNING = 'BUDGET_WARNING',
  BUDGET_EXCEEDED = 'BUDGET_EXCEEDED',
}
